#! /bin/sh

bash ~/change_to_dvorak.sh &
pgrep -x sxhkd > /dev/null || sxhkd &

picom &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^9' follow=on
bspc rule -a zen desktop='^1' follow=on
bspc rule -a vlc desktop='^0' follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a opengl desktop='^1' state=floating follow=on

feh --bg-scale ~/Downloads/wall.png &
zen-browser &
