#! /bin/sh

bash ~/change_to_dvorak.sh &
pgrep -x sxhkd > /dev/null || sxhkd &

picom &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Window borders
bspc config border_width 3       # width in pixels
bspc config window_gap 10        # gap between windows
bspc config focused_border_color "#ff5555"   # color of focused window
bspc config normal_border_color  "#44475a"   # color of unfocused windows

bspc rule -a Gimp desktop='^9' follow=on
bspc rule -a zen desktop='^1' follow=on
bspc rule -a vlc desktop='^0' follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a opengl state=floating 

# Friday workspace routing
bspc rule -a kitty:friday-term desktop='^3'
bspc rule -a kitty:friday-nvim desktop='^8'

feh --bg-scale ~/.config/wallpapers/retro_vibe_setup.png &
zen-browser &
kitty &
xset r rate 200 35 &

